[project]
authors = ["Pierre Poulain <pierre.poulain@cupnet.net>"]
channels = ["conda-forge", "nodefaults"]
description = "Play with Software Heritage API"
name = "jupyterlab"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
jupyterlab = "jupyter lab"

[dependencies]
python = ">=3.11"
jupyterlab = ">=4"
requests = "*"
watermark = "*"
